### ISSUE TITLE
Linux support (Ubuntu 16.04)

### ISSUE THREAD

**Issue by emmenlau** [SCIInstitute/fluorender#4]
Fluorender looks very interesting! I would like to try it on my data, but I only have Linux. There seems
to be no Linux support. If I add Linux support,would you be willing to consider such a pull request?

I already got to ~78% of the build. Until now there where mostly some minor issues with some missing
header includes, or uppercase/lowercase file name issues, and minor issues in the CMakeLists.txt.
Now I got to the first "real" problem: there is class `KeyCode` defined in `Animator/FlKey.h`. This name
collides with a name in:
```
/usr/include/X11/X.h:108:23: note: ‘KeyCode’ has a previous declaration here
 typedef unsigned char KeyCode;
```
To build on Linux I think its required to rename the class `KeyCode` to something else. Is that an
option?

**Comment by emmenlau** [comment]
Ok I have a first working version that can do 3D rendering. Quite a number of smaller issues needed to be addressed. Is this interesting for you?

**Comment by emmenlau** [comment]
If I make a pull request, should I base it off of master or the experimental branch?

**Comment by basisunus** [comment]
@emmenlau Brig set up the github repository for the FluoRender project. I'm working based on the existing protocols. Considering there are few FluoRender users actually using Linux, we haven't had support for Linux. I personally don't have a Linux computer to work with. But you're welcome to contribute however you think is appropriate. The experimental branch is what I'm adding new features to FluoRender. Once the features have accumulated to a certain amount and tested to be stable, they are merged with the master for a new release. You can either keep your own branch and we can provide a link on our project page, or you can send a pull request. I'll see what I can do. You are certainly more familiar with git/github than I am. Thank you for your support and help.

**Comment by emmenlau** [comment]
Dear @basisunus , thanks for the kind reply! I'm also just learning git, and its not too easy :-)

Here are my changes for Linux support: https://github.com/SCIInstitute/fluorender/pull/5
I am pretty certain that my changes in the C++ code files should not hurt other platforms.
But for my changes in the `CMakeLists.txt`, it might be good if you test them to be sure they
do no harm. Its not big changes, but I could not test on Mac OS and not on Windows, only
Linux.

**Comment by basisunus** [comment]
i tested on Apple and Windows. I turned on the static lib for boost, which is how I used it before. Otherwise, it seems working. Thanks.

**Comment by emmenlau** [comment]
Great, I'm happy that it works! It also works on Ubuntu 16.04 quite well, no problems so far!
