### ISSUE TITLE
Mailing list refusing access

### ISSUE THREAD

**Issue by bscott711** [SCIInstitute/fluorender#7]
I have tried to join the fluorender-users mailing list on two occassions (following the instructions on the website), and I get an error saing that it is undeliverable due to the recipient system refusing to accept a connection.... any help is appreciated. 

Instructions that were followed:
Joining the FluoRender Users Mailing List
1. Compose an email to sympa@lists.sci.utah.edu with the following in the body of message: subscribe fluorender-users
Nothing needed in the Subject line. Just send.
2. You will receive a response from the list manager requesting confirmation. Just send back a reply message to confirm your subscription (no added text needed).
3. Finally, you will receive a welcome message confirming that you have been added to the mailing list.

**Comment by basisunus** [comment]
What's your email? You can send it to wanyong@cs.utah.edu. I can add you to the list

**Comment by jessdtate** [comment]
The list name is fluorender, instead of fluorender-users. We need to update the website.
